---
- name: Stop tomcat-{{ tomcat_application_name }}
  shell: sh /var/crontab/restart_tomcat.sh tomcat-{{ tomcat_application_name }} stop
  
- name: delete tomcat-{{ tomcat_application_name }} dir
  shell: rm -rf /u01/tomcat-{{ tomcat_application_name }}
  
- name: delete tomcat-{{ tomcat_application_name }} log
  shell: rm -rf /u01/httpd/{{ tomcat_application_name }}*
  
- name: delete tomcat-{{ tomcat_application_name }} javacode
  shell: rm -rf /u01/javacode/{{ tomcat_application_name }}
